# Generated by Django 4.2.11 on 2026-05-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shop",
            new_name="shops_shop_status_485b2a_idx",
            old_name="shops_shop_status_d8d1d2_idx",
        ),
        migrations.RenameIndex(
            model_name="shop",
            new_name="shops_shop_city_0942b1_idx",
            old_name="shops_shop_city_621611_idx",
        ),
        migrations.AddField(
            model_name="shop",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="shop",
            name="shop_logo",
            field=models.ImageField(blank=True, null=True, upload_to="shop_logos/"),
        ),
    ]
