# Generated by Django 4.2.11 on 2026-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_area_booking_city_booking_landmark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
    ]
