# Generated by Django 4.2.11 on 2026-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_bookingmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="bookingmessage",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="bookingmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
