# Generated by Django 4.2.11 on 2026-05-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_shop_gst_logo"),
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("booking", "Booking"),
                    ("invoice", "Invoice"),
                    ("customer", "Customer"),
                    ("product", "Product"),
                    ("technician", "Technician"),
                    ("user", "User"),
                    ("", "None"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="shops.shop",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Booking Created"),
                    ("booking_assigned", "Booking Assigned"),
                    ("booking_in_progress", "Booking In Progress"),
                    ("booking_completed", "Booking Completed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("invoice_created", "Invoice Created"),
                    ("payment_received", "Payment Received"),
                    ("low_stock", "Low Stock Alert"),
                    ("purchase_received", "Purchase Received"),
                    ("user_created", "User Created"),
                    ("permission_changed", "Permission Changed"),
                    ("system", "System"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["shop", "created_at"], name="notificatio_shop_id_2ed894_idx"
            ),
        ),
    ]
