# Generated by Django 4.2.11 on 2026-05-19 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technicians", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="technicianavailability",
            index=models.Index(
                fields=["technician", "date"], name="technicians_technic_ec2c1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="technicianavailability",
            unique_together={("technician", "date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="technician",
            index=models.Index(
                fields=["availability_status"], name="technicians_availab_9077f1_idx"
            ),
        ),
    ]
