# Generated by Django 4.2.11 on 2026-05-23 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_shop_gst_logo"),
        ("services", "0002_service_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="🔧", max_length=10)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="service",
            new_name="services_se_shop_id_7d44c7_idx",
            old_name="services_se_shop_id_68de9e_idx",
        ),
        migrations.AddField(
            model_name="service",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=18,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="estimated_duration",
            field=models.IntegerField(
                help_text="Duration in minutes",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_available"], name="services_se_is_avai_db1380_idx"
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_categories",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category"], name="services_se_categor_7ca2f8_idx"
            ),
        ),
    ]
