# Generated by Django 4.2.11 on 2026-05-19 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("customers", "Customers"),
                            ("bookings", "Bookings"),
                            ("inventory", "Inventory"),
                            ("services", "Services"),
                            ("staff", "Staff"),
                            ("billing", "Billing"),
                            ("reports", "Reports"),
                            ("suppliers", "Suppliers"),
                            ("expenses", "Expenses"),
                            ("technicians", "Technicians"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("export_csv", "Export CSV"),
                            ("manage_staff", "Manage Staff"),
                            ("manage_inventory", "Manage Inventory"),
                            ("manage_services", "Manage Services"),
                            ("manage_bookings", "Manage Bookings"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Permission",
                "verbose_name_plural": "Manager Permissions",
                "ordering": ["manager", "module", "action"],
                "unique_together": {("manager", "module", "action")},
            },
        ),
    ]
