# Generated by Django 4.2.11 on 2026-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_staff_permission_scope"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_shop_id_ee128f_idx",
            old_name="users_user_shop_id_97deaa_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="face_encoding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="face_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_face_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
