# Generated by Django 4.2.11 on 2026-05-19 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["user"], name="customers_c_user_id_c1d57c_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["city"], name="customers_c_city_571324_idx"),
        ),
    ]
