# Generated by Django 4.2.11 on 2026-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="preferred_contact",
            field=models.CharField(
                choices=[("phone", "Phone"), ("email", "Email"), ("sms", "SMS")],
                default="phone",
                max_length=20,
            ),
        ),
    ]
