# Generated by Django 4.2.11 on 2026-05-19 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_bookings", models.IntegerField(default=0)),
                ("completed_bookings", models.IntegerField(default=0)),
                ("pending_bookings", models.IntegerField(default=0)),
                ("total_products_sold", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Daily Metrics",
                "verbose_name_plural": "Daily Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Report"),
                            ("profit_loss", "Profit & Loss"),
                            ("inventory", "Inventory Report"),
                            ("staff_performance", "Staff Performance"),
                            ("customer_activity", "Customer Activity"),
                            ("technician_performance", "Technician Performance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("data", models.JSONField(default=dict)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("created_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-generated_date"],
            },
        ),
    ]
